# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EofVar <- function(ObsTrack, Pred, C, usecores, verbose) {
    .Call(`_RLT_EofVar`, ObsTrack, Pred, C, usecores, verbose)
}

ForestKernelUni_Self <- function(NodeType, SplitVar, SplitValue, LeftNode, RightNode, NodeSize, X, Ncat, usecores, verbose) {
    .Call(`_RLT_ForestKernelUni_Self`, NodeType, SplitVar, SplitValue, LeftNode, RightNode, NodeSize, X, Ncat, usecores, verbose)
}

ForestKernelUni_Cross <- function(NodeType, SplitVar, SplitValue, LeftNode, RightNode, NodeSize, XTest, XTrain, Ncat, ObsTrack, usecores, verbose) {
    .Call(`_RLT_ForestKernelUni_Cross`, NodeType, SplitVar, SplitValue, LeftNode, RightNode, NodeSize, XTest, XTrain, Ncat, ObsTrack, usecores, verbose)
}

GraphClaForestMultiFit <- function(X, Y, Ncat, param, RLTparam, obsweight, varweight, usecores, verbose, ObsTrack) {
    .Call(`_RLT_GraphClaForestMultiFit`, X, Y, Ncat, param, RLTparam, obsweight, varweight, usecores, verbose, ObsTrack)
}

GraphClaForestMultiPred <- function(NodeType, SplitVar, SplitLoading, SplitValue, LeftNode, RightNode, NodeSize, NodeAve, X, Ncat, treeindex, keep_all, usecores, verbose) {
    .Call(`_RLT_GraphClaForestMultiPred`, NodeType, SplitVar, SplitLoading, SplitValue, LeftNode, RightNode, NodeSize, NodeAve, X, Ncat, treeindex, keep_all, usecores, verbose)
}

GraphKernel_Self <- function(NodeType, SplitVar, SplitLoading, SplitValue, LeftNode, RightNode, NodeSize, NodeAve, X, Ncat, verbose) {
    .Call(`_RLT_GraphKernel_Self`, NodeType, SplitVar, SplitLoading, SplitValue, LeftNode, RightNode, NodeSize, NodeAve, X, Ncat, verbose)
}

GraphKernel_Cross <- function(NodeType, SplitVar, SplitLoading, SplitValue, LeftNode, RightNode, NodeSize, NodeAve, X1, X2, Ncat, verbose) {
    .Call(`_RLT_GraphKernel_Cross`, NodeType, SplitVar, SplitLoading, SplitValue, LeftNode, RightNode, NodeSize, NodeAve, X1, X2, Ncat, verbose)
}

GraphKernel_Train <- function(NodeType, SplitVar, SplitLoading, SplitValue, LeftNode, RightNode, NodeSize, NodeAve, X1, X2, Ncat, ObsTrack, verbose) {
    .Call(`_RLT_GraphKernel_Train`, NodeType, SplitVar, SplitLoading, SplitValue, LeftNode, RightNode, NodeSize, NodeAve, X1, X2, Ncat, ObsTrack, verbose)
}

RegForestUniFit <- function(X, Y, Ncat, param, RLTparam, obsweight, varweight, usecores, verbose, ObsTrack) {
    .Call(`_RLT_RegForestUniFit`, X, Y, Ncat, param, RLTparam, obsweight, varweight, usecores, verbose, ObsTrack)
}

RegForestUniPred <- function(NodeType, SplitVar, SplitValue, LeftNode, RightNode, NodeSize, NodeAve, X, Ncat, treeindex, keep_all, usecores, verbose) {
    .Call(`_RLT_RegForestUniPred`, NodeType, SplitVar, SplitValue, LeftNode, RightNode, NodeSize, NodeAve, X, Ncat, treeindex, keep_all, usecores, verbose)
}

SurvForestUniFit <- function(X, Y, Censor, Ncat, param, RLTparam, obsweight, varweight, usecores, verbose, ObsTrack) {
    .Call(`_RLT_SurvForestUniFit`, X, Y, Censor, Ncat, param, RLTparam, obsweight, varweight, usecores, verbose, ObsTrack)
}

SurvForestUniPred <- function(NodeType, SplitVar, SplitValue, LeftNode, RightNode, NodeSize, NodeHaz, X, Ncat, NFail, treeindex, keep_all, usecores, verbose) {
    .Call(`_RLT_SurvForestUniPred`, NodeType, SplitVar, SplitValue, LeftNode, RightNode, NodeSize, NodeHaz, X, Ncat, NFail, treeindex, keep_all, usecores, verbose)
}

cindex_d <- function(Y, Censor, pred) {
    .Call(`_RLT_cindex_d`, Y, Censor, pred)
}

ARMA_EMPTY_UMAT <- function() {
    .Call(`_RLT_ARMA_EMPTY_UMAT`)
}

ARMA_EMPTY_VEC <- function() {
    .Call(`_RLT_ARMA_EMPTY_VEC`)
}

